### PR TITLE
Fix / Migration script / ts_template_time_savings table not found

### PR DESCRIPTION
**Pull request by ionSurf**
Provides fix to migration script when attempting to create ts_template_time_savings. Previously, the script would only install the table if using a postgreSQL database.

### CODE REVIEW

**Comment by tduniec** [comment]
Hey, 

thanks for contribution. 
I cans see your changes, but in case uuid extension is not configured for other db types likes SQLlite. 
We need to add logic to generate UUID during insert to SQLite type db table. In postgres it was PostgresSQL responsibility to add new UUID value on very insert. 

it is using simple insert here 
https://github.com/tduniec/backstage-timesaver-plugin/blob/main/plugins/time-saver-backend/src/timeSaver/handler.ts

**Comment by ionSurf** [comment]
@tduniec, what's the best way to reach you?

**Comment by toma2395** [comment]
You can reach me on mail: tomekduniec@gmail.com, discord: tduni8

**Comment by tduniec** [comment]
We can chat to discuss this change further

**Pull request closed without merging**
